# Generated by Django 4.2 on 2023-07-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_my_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_user',
        ),
    ]
